# Generated by Django 4.2.5 on 2023-09-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="age",
        ),
    ]
