# Generated by Django 4.2.5 on 2023-09-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0002_remove_person_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="last_name",
        ),
    ]
